<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Wrapping Errors in Go - How to Handle Nested Errors | Rahul Vishwakarma Blog</title>
    <link rel="stylesheet" type="text/css" href="../styles.css" media="screen" />
</head>
<body>
<header>
    <nav>
        <a href="/index.html" aria-label="Go back to the homepage">‚Üê Back</a>
        <a href="https://blog.boot.dev/golang/wrapping-errors-in-go-how-to-handle-nested-errors/" target="_blank" rel="noopener noreferrer">
            View Original
        </a>
    </nav>
</header>

<main>
    <article>
        <h1>Wrapping Errors in Go - How to Handle Nested Errors</h1>
        <section>
            
            <div id="readability-page-1" class="page"><div>
           <p>Errors in Go are a hot topic. Many newcomers to the language immediately level their first criticism, ‚Äúerrors in go are clunky! Let me just use try/catch!‚Äù This criticism is well-meaning but misguided.</p>
<p>The paradigm of errors as a <em>type</em>, rather than something to be <em>thrown</em>, simplifies error handling and brings it to the forefront. It also forces developers to think about errors at every step.</p>
<blockquote>
<p>What will go wrong here? How should I handle it?</p>
</blockquote>
<p>There are plenty of articles that discuss the pros/cons of error handling in Go. I want to talk specifically about how the verbose (but better) handling of errors in Go can lead to a common problem: deeply nested errors.</p>
<h2 id="the-called-function">
  <span> The Called Function</span> <a href="#the-called-function">üîó</a></h2>
<p>To demonstrate the problem of nested errors, let‚Äôs take a look at the following function:</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>func</span> <span>isInRange</span><span>(</span><span>i</span> <span>int</span><span>)</span> <span>error</span> <span>{</span>
</span></span><span><span>	<span>const</span> <span>min</span> <span>=</span> <span>5</span>
</span></span><span><span>	<span>const</span> <span>max</span> <span>=</span> <span>10</span>
</span></span><span><span>	<span>if</span> <span>i</span> <span>&lt;</span> <span>5</span> <span>||</span> <span>i</span> <span>&gt;</span> <span>10</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;isInRange: %v must be between %v and %v&#34;</span><span>,</span> <span>i</span><span>,</span> <span>min</span><span>,</span> <span>max</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>return</span> <span>nil</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p><code>isInRange()</code> is a simple function that checks if a number is between two other predefined numbers, and returns a formatted error message in case the number is out of range.</p>
<h2 id="the-calling-function">
  <span> The Calling Function</span> <a href="#the-calling-function">üîó</a></h2>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>func</span> <span>getNumberFromStdIn</span><span>()</span> <span>(</span><span>int</span><span>,</span> <span>error</span><span>)</span> <span>{</span>
</span></span><span><span>	<span>reader</span> <span>:=</span> <span>bufio</span><span>.</span><span>NewReader</span><span>(</span><span>os</span><span>.</span><span>Stdin</span><span>)</span>
</span></span><span><span>	<span>text</span><span>,</span> <span>_</span><span>,</span> <span>err</span> <span>:=</span> <span>reader</span><span>.</span><span>ReadLine</span><span>()</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>err</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>i</span><span>,</span> <span>err</span> <span>:=</span> <span>strconv</span><span>.</span><span>Atoi</span><span>(</span><span>string</span><span>(</span><span>text</span><span>))</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>err</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>err</span> <span>=</span> <span>isInRange</span><span>(</span><span>i</span><span>)</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>err</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>return</span> <span>i</span><span>,</span> <span>nil</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p>As you can see, <code>getNumberFromStdIn()</code> calls <code>isInRange()</code>. The problem with the above code is that if an error happens within <code>getNumberFromStdIn()</code> and subsequently is logged to the console, it is almost impossible to tell where the error came from.</p>
<p>For example, if <code>isInRange</code>‚Äôs error is logged to the console during execution:</p>
<pre tabindex="0"><code>isInRange: 3 must be between 5 and 10
</code></pre><p>Where did this come from? We know that <code>isInRange()</code> created the error, but we don‚Äôt know where <code>isInRange()</code> was called. Was <code>isInRange()</code> called by <code>getNumberFromStdIn()</code>? Or somewhere else? Perhaps we grep through our codebase and see that <code>isInRange()</code> is called hundreds of times! Now our task to find the root of the error becomes much more difficult than it needs to be.</p>
<h2 id="the-solution-wrap-the-errors-with-some-context">
  <span> The solution? Wrap the errors with some context</span> <a href="#the-solution-wrap-the-errors-with-some-context">üîó</a></h2>
<p>The <a href="https://pkg.go.dev/fmt#Errorf">fmt.Errorf()</a> function is a favorite of mine, I use it in most functions I write. It allows us to format error messages, and more importantly to wrap errors within each other, which has the nice benefit of our error messages looking more like stack traces.</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>func</span> <span>getNumberFromStdIn</span><span>()</span> <span>(</span><span>int</span><span>,</span> <span>error</span><span>)</span> <span>{</span>
</span></span><span><span>	<span>reader</span> <span>:=</span> <span>bufio</span><span>.</span><span>NewReader</span><span>(</span><span>os</span><span>.</span><span>Stdin</span><span>)</span>
</span></span><span><span>	<span>text</span><span>,</span> <span>_</span><span>,</span> <span>err</span> <span>:=</span> <span>reader</span><span>.</span><span>ReadLine</span><span>()</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;reader.ReadLine: %w&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>i</span><span>,</span> <span>err</span> <span>:=</span> <span>strconv</span><span>.</span><span>Atoi</span><span>(</span><span>string</span><span>(</span><span>text</span><span>))</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;strconv.Atoi: %w&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>err</span> <span>=</span> <span>isInRange</span><span>(</span><span>i</span><span>)</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span> <span>{</span>
</span></span><span><span>		<span>return</span> <span>0</span><span>,</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;isInRange: %w&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>return</span> <span>i</span><span>,</span> <span>nil</span>
</span></span><span><span><span>}</span>
</span></span><span><span>
</span></span><span><span><span>func</span> <span>runMainThread</span><span>()</span> <span>error</span> <span>{</span>
</span></span><span><span>	<span>i</span><span>,</span> <span>err</span> <span>:=</span> <span>getNumberFromStdIn</span><span>()</span>
</span></span><span><span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span><span>{</span>
</span></span><span><span>		<span>return</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;getNumberFromStdIn: %w&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p>Now, when <code>isInRange()</code> is called in this specific location, we get a formatted message:</p>
<pre tabindex="0"><code>getNumberFromStdIn: isInRange: 3 must be between 5 and 10
</code></pre><p>By wrapping errors and building well-formatted error messages, we can keep better track of where errors are happening. I often just add the name of the function being called to my error messages, but we can make the message say whatever we want. For example, I‚Äôll often include parameter information in the error so I know which inputs caused the error.</p>
<h2 id="why-use-w">
  <span> Why use %w?</span> <a href="#why-use-w">üîó</a></h2>
<p>For quite a while I was using <code>%v</code> as the interpolated value in the <code>fmt.Errorf</code> function, and for the most part it worked as intended. The problem with <code>%v</code> really only arises when it comes time to compare two errors using the <a href="https://pkg.go.dev/errors#Is">errors.Is</a> function. For example. I‚Äôll often want to check if a error as an ‚Äúend of file‚Äù error, so I‚Äôll use the following check:</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>if</span> <span>errors</span><span>.</span><span>Is</span><span>(</span><span>err</span><span>,</span> <span>io</span><span>.</span><span>EOF</span><span>)</span> <span>{</span>
</span></span><span><span>	<span>fmt</span><span>.</span><span>Println</span><span>(</span><span>&#34;Reading file finished...&#34;</span><span>)</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p>This code would fail the error check:</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>func</span> <span>readFile</span><span>()</span> <span>([]</span><span>byte</span><span>,</span> <span>error</span><span>){</span>
</span></span><span><span>	<span>dat</span><span>,</span> <span>err</span> <span>:=</span> <span>readLine</span><span>()</span> <span>// returns io.EOF error
</span></span></span><span><span><span></span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span><span>{</span>
</span></span><span><span>		<span>// %v ruins the wrap, and future
</span></span></span><span><span><span></span>		<span>// errors.Is checks will fail for type io.EOF
</span></span></span><span><span><span></span>		<span>return</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;readLine: %v&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>return</span> <span>dat</span><span>,</span> <span>nil</span>
</span></span><span><span><span>}</span>
</span></span><span><span>
</span></span><span><span><span>_</span><span>,</span> <span>err</span> <span>=</span> <span>readFile</span><span>()</span>
</span></span><span><span><span>if</span> <span>errors</span><span>.</span><span>Is</span><span>(</span><span>err</span><span>,</span> <span>io</span><span>.</span><span>EOF</span><span>)</span> <span>{</span>
</span></span><span><span>	<span>// this will NOT execute
</span></span></span><span><span><span></span>	<span>fmt</span><span>.</span><span>Println</span><span>(</span><span>&#34;Reading file finished...&#34;</span><span>)</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p>Instead, we can preserve the error check by using <code>%w</code>:</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>func</span> <span>readFile</span><span>()</span> <span>([]</span><span>byte</span><span>,</span> <span>error</span><span>){</span>
</span></span><span><span>	<span>dat</span><span>,</span> <span>err</span> <span>:=</span> <span>readLine</span><span>()</span> <span>// returns io.EOF error
</span></span></span><span><span><span></span>	<span>if</span> <span>err</span> <span>!=</span> <span>nil</span><span>{</span>
</span></span><span><span>		<span>return</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;readLine: %w&#34;</span><span>,</span> <span>err</span><span>)</span>
</span></span><span><span>	<span>}</span>
</span></span><span><span>	<span>return</span> <span>dat</span><span>,</span> <span>nil</span>
</span></span><span><span><span>}</span>
</span></span><span><span>
</span></span><span><span><span>_</span><span>,</span> <span>err</span> <span>=</span> <span>readFile</span><span>()</span>
</span></span><span><span><span>if</span> <span>errors</span><span>.</span><span>Is</span><span>(</span><span>err</span><span>,</span> <span>io</span><span>.</span><span>EOF</span><span>)</span> <span>{</span>
</span></span><span><span>	<span>// this will execute
</span></span></span><span><span><span></span>	<span>fmt</span><span>.</span><span>Println</span><span>(</span><span>&#34;Reading file finished...&#34;</span><span>)</span>
</span></span><span><span><span>}</span>
</span></span></code></pre></div><p>As far as I know, when working with errors it‚Äôs <em>always better</em> to use <code>%w</code> over <code>%v</code>.</p>
<h2 id="manually-unwrapping-errors">
  <span> Manually unwrapping errors</span> <a href="#manually-unwrapping-errors">üîó</a></h2>
<p>To be honest, I‚Äôve never felt the need to manually unwrap an error. That said, I‚Äôm sure there are cases where you would want to do so. The standard library provides <a href="https://pkg.go.dev/errors#Unwrap">errors.Unwrap</a> to do just that.</p>
<div><pre tabindex="0"><code data-lang="go"><span><span><span>err1</span> <span>:=</span> <span>errors</span><span>.</span><span>New</span><span>(</span><span>&#34;no user id provided&#34;</span><span>)</span>
</span></span><span><span><span>err2</span> <span>:=</span> <span>fmt</span><span>.</span><span>Errorf</span><span>(</span><span>&#34;error on cronos server: [%w]&#34;</span><span>,</span> <span>err1</span><span>)</span>
</span></span><span><span><span>fmt</span><span>.</span><span>Println</span><span>(</span><span>err2</span><span>)</span>
</span></span><span><span><span>// prints: &#34;error on cronos server: [no user id provided]&#34;
</span></span></span><span><span><span></span><span>fmt</span><span>.</span><span>Println</span><span>(</span><span>errors</span><span>.</span><span>Unwrap</span><span>(</span><span>err2</span><span>))</span>
</span></span><span><span><span>// prints: &#34;no user id provided&#34;
</span></span></span></code></pre></div><p>As an example, I might wrap an error with some sensitive context that‚Äôs useful to my internal team, but maybe we need to unwrap it before returning it over an HTTP API for security purposes.</p>
<h2 id="should-i-always-wrap-errors">
  <span> Should I always wrap errors?</span> <a href="#should-i-always-wrap-errors">üîó</a></h2>
<p>Like all rules of thumb, there are exceptions.</p>
<p>For example, if I‚Äôm writing a package that exposes the function <code>getNumberFromStdIn()</code> then my users (programmers using my package) don‚Äôt need to know that <code>atoi()</code> failed, they just need to know that <code>getNumberFromStdIn()</code> failed. I probably don‚Äôt want to be exposing too much internal logic to my API users. I can probably ignore the underlying error and create my own message from scratch that‚Äôs more helpful to the end user.</p>
<p>If it is glaringly obvious where an error comes from, there is also less reason to wrap it. Wrapping an error, in theory, should never hurt, but it <em>can</em> be unnecessarily verbose and a lot of extra work. As always, look at everything on a case-by-case basis.</p>
  

<div>
  <h3>Find a problem with this article?</h3>
  <p><a target="_blank" href="https://github.com/bootdotdev/blog/issues">Report an issue on GitHub</a>
</p></div>
 
        </div></div>
        </section>
    </article>
</main>
</body>
</html>
